---

- name: Install Node Exporter
  hosts: all
  become: true
  tasks:
    - name: Download Node Exporter binary
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"
      vars:
        node_exporter_version: "0.18.1"

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/opt/"
        remote_src: yes
        creates: "/opt/node_exporter-{{ node_exporter_version }}"

    - name: Create a symbolic link
      file:
        src: "/opt/node_exporter-{{ node_exporter_version }}/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        state: link

    - name: Create systemd service for Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes
        unit:
          after: network.target
        service:
          exec_start: /usr/local/bin/node_exporter