---


- hosts: presta
  become: true

  tasks:
    - name: Create workstation directory insisde tmp
      ansible.builtin.file:
        path: /tmp/workstation
        state: directory
      tags:
        - docker

    - name: Create prestashop directory inside workstation
      ansible.builtin.file:
        path: /tmp/workstation/prestashop
        state: directory
      tags:
        - docker

    - name: Create code directory inside prestashop
      ansible.builtin.file:
        path: /tmp/workstation/prestashop/code
        state: directory
      tags:
        - docker

    - name: Create manifest directory inside prestashop
      ansible.builtin.file:
        path: /tmp/workstation/prestashop/manifest
        state: directory
      tags:
        - directory


    - name: Install Docker prerequisites
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags:
        - docker

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Verify that we have the key with the fingerprint
      ansible.builtin.apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Set up the stable repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - docker

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add remote "thed" user to "docker" group
      ansible.builtin.user:
        name: "thed"
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Install docker-compose
      ansible.builtin.get_url: 
        url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Copy code from control machine to server
      ansible.builtin.copy:
        src: /home/marcin/presta/maria
        dest: /tmp/workplace/prestashop/code
        remote_src: false
      tags:
        - copy

    - name: Copy docker-compose from contorl machine to server
      ansible.builtin.copy:
        src: /home/marcin/pro/biznes-elektroniczny/docker-compose.yml
        dest: /tmp/workstation/prestashop/manifest/
        remote_src: false
      tags:
        - copy

    - name: Run manifest
      ansible.builtin.command:
        chdir: /tmp/workstation/prestashop/manifest
        cmd: docker-compose up -d
      tags:
        - manifest