---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: allways
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu/Linux Mint)
    tags: allways
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: upgrade
    apt:
      upgrade: dist

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php
    tags: apache,apache2,ubuntu,linuxmint
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Linux Mint"]

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: db,mariadb,ubuntu,linuxmint
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Linux Mint"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

